/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import okhttp3.FormBody;
import okhttp3.RequestBody;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Christian
 */
public class Principal extends javax.swing.JPanel {

    Cliente cliente = new Cliente();
    JSONArray estudiantes;
    static String seleccion;
    static Color bkColor;

    public Principal() {
        initComponents();
        this.bkColor = new Color(255, 204, 255);
        fillData();
        seleccionInicial();
    }

    private void fillData() {
        JSONObject data = cliente.getJSON("https://proyectosuta.000webhostapp.com/aos_proyecto/models2/acceder.php");
        estudiantes = (JSONArray) data.get("estudiantes");
        for (int i = 0; i < estudiantes.length(); i++) {
            Estudiante estudiante = new Estudiante();
            JSONObject estudianteJson = (JSONObject) this.estudiantes.get(i);
            estudiante.setCedula(estudianteJson.getString("EST_CEDULA"));
            estudiante.setNombre(estudianteJson.getString("EST_NOMBRE"));
            estudiante.setApellido(estudianteJson.getString("EST_APELLIDO"));
            estudiante.setTelefono(estudianteJson.getString("EST_TELEFONO"));
            estudiante.setDireccion(estudianteJson.getString("EST_DIRECCION"));
            crearFicha(estudiante, i);
        }
    }

    private void seleccionInicial() {
        for (int i = 0; i < jpnlEstudiantes.getComponentCount(); i++) {
            if (i == 0) {
                ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getBkFicha().setBackground(bkColor);
                seleccion = ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getEstudiante().getCedula();
            } else {
                ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getBkFicha().setBackground(Color.white);
            }
        }
    }

    private void crearFicha(Estudiante estudiante, int position) {
        FichaEstudiante ficha = new FichaEstudiante(estudiante);
        jpnlEstudiantes.add(ficha).setBounds(0, 112 * position, 605, 112);
        jpnlEstudiantes.setPreferredSize(new Dimension(605, 112 * position));
    }

    private void editarEstudiante() {
        Estudiante estudiante = new Estudiante();
        for (int i = 0; i < jpnlEstudiantes.getComponentCount(); i++) {
            if (((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getBkFicha().getBackground().getRGB() == -13057) {
                estudiante = ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getEstudiante();
                break;
            }
        }
        PanelPrincipal.redefinirPanelContenido(new EditarEstudiante(estudiante));
    }

    public static void seleccionarRegistro(String id) {
        for (int i = 0; i < jpnlEstudiantes.getComponentCount(); i++) {
            if (((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getEstudiante().getCedula().equals(id)) {
                ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getBkFicha().setBackground(bkColor);
                seleccion = ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getEstudiante().getCedula();
            } else {
                ((FichaEstudiante) jpnlEstudiantes.getComponent(i)).getBkFicha().setBackground(Color.white);
            }
        }
    }

    private void confirmarEliminar() {
        if (JOptionPane.showConfirmDialog(new JInternalFrame(), "¿Estás seguro?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            eliminarEstudiante(seleccion);
            PanelPrincipal.redefinirPanelContenido(new Principal());
            this.seleccionInicial();
        }
    }
    
    private void eliminarEstudiante(String id) {
        Cliente cliente = new Cliente();
        RequestBody requestBody = new FormBody.Builder().add("EST_CEDULA", id).build();
        JSONObject response = cliente.postJSON("https://proyectosuta.000webhostapp.com/aos_proyecto/models2/eliminar.php", requestBody);
        boolean verificar = response.getBoolean("ok");
        if (verificar) {
            JOptionPane.showMessageDialog(this, "Se eliminó correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se eliminó el estudiante");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtBienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpnlEstudiantes = new javax.swing.JPanel();
        jpnlEliminar = new javax.swing.JPanel();
        jtxtEliminar = new javax.swing.JLabel();
        jlblBotonEliminar = new javax.swing.JLabel();
        jpnlEditar = new javax.swing.JPanel();
        jtxtEditar = new javax.swing.JLabel();
        jlblBotonEditar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(415, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPerfil.setBackground(new java.awt.Color(255, 51, 51));
        jpnlPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE GESTIÓN");
        jpnlPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 225, 30));

        jtxtBienvenida.setFont(new java.awt.Font("Poppins SemiBold", 0, 32)); // NOI18N
        jtxtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jtxtBienvenida.setText("Estudiantes (UTA)");
        jpnlPerfil.add(jtxtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 67, 579, 40));

        add(jpnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, 130));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpnlEstudiantes.setPreferredSize(new java.awt.Dimension(621, 585));

        javax.swing.GroupLayout jpnlEstudiantesLayout = new javax.swing.GroupLayout(jpnlEstudiantes);
        jpnlEstudiantes.setLayout(jpnlEstudiantesLayout);
        jpnlEstudiantesLayout.setHorizontalGroup(
            jpnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jpnlEstudiantesLayout.setVerticalGroup(
            jpnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpnlEstudiantes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 623, 390));

        jpnlEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jpnlEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEliminar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jtxtEliminar.setForeground(new java.awt.Color(171, 26, 32));
        jtxtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtEliminar.setText("ELIMINAR");
        jtxtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEliminarMouseClicked(evt);
            }
        });
        jpnlEliminar.add(jtxtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 180, 45));

        jlblBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buttonB_180_45.png"))); // NOI18N
        jpnlEliminar.add(jlblBotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        add(jpnlEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 45));

        jpnlEditar.setBackground(new java.awt.Color(255, 255, 255));
        jpnlEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEditar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jtxtEditar.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtEditar.setText("EDITAR");
        jtxtEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEditarMouseClicked(evt);
            }
        });
        jpnlEditar.add(jtxtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        jlblBotonEditar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jlblBotonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jlblBotonEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblBotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_180_45.png"))); // NOI18N
        jlblBotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnlEditar.add(jlblBotonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 45));

        add(jpnlEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 530, 180, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEliminarMouseClicked
        confirmarEliminar();
    }//GEN-LAST:event_jtxtEliminarMouseClicked

    private void jtxtEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarMouseClicked
        editarEstudiante();
    }//GEN-LAST:event_jtxtEditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblBotonEditar;
    private javax.swing.JLabel jlblBotonEliminar;
    private javax.swing.JPanel jpnlEditar;
    private javax.swing.JPanel jpnlEliminar;
    private static javax.swing.JPanel jpnlEstudiantes;
    private javax.swing.JPanel jpnlPerfil;
    private javax.swing.JLabel jtxtBienvenida;
    private javax.swing.JLabel jtxtEditar;
    private javax.swing.JLabel jtxtEliminar;
    // End of variables declaration//GEN-END:variables
}
